/**
 * Data Export and Analytics Functions
 */

// ===== CSV EXPORT =====
function exportMeasurements() {
  try {
    if (AppState.measurements.length === 0) {
      alert('No measurements to export');
      return;
    }

    const csvContent = generateCSV(AppState.measurements);
    downloadFile(csvContent, 'measurements.csv', 'text/csv');
  } catch (error) {
    console.error('Error exporting measurements:', error);
    alert('Error exporting measurements');
  }
}

function exportAllCSV() {
  try {
    // Placeholder: Export all session data as CSV
    const data = {
      measurements: AppState.measurements,
      timestamp: new Date().toISOString(),
    };

    const csvContent = JSON.stringify(data, null, 2);
    downloadFile(csvContent, 'all-data.csv', 'text/csv');
  } catch (error) {
    console.error('Error exporting all CSV:', error);
    alert('Error exporting data');
  }
}

// ===== JSON EXPORT =====
function exportJSON() {
  try {
    const data = {
      measurements: AppState.measurements,
      annotations: AppState.annotations,
      calibration: AppState.pixPerUm,
      timestamp: new Date().toISOString(),
      version: '1.0',
    };

    const jsonContent = JSON.stringify(data, null, 2);
    downloadFile(jsonContent, 'phenotyping-data.json', 'application/json');
  } catch (error) {
    console.error('Error exporting JSON:', error);
    alert('Error exporting JSON');
  }
}

// ===== REPORT EXPORT =====
function exportReportTxt() {
  try {
    const reportContent = generateReport();
    downloadFile(reportContent, 'phenotyping-report.txt', 'text/plain');
  } catch (error) {
    console.error('Error exporting report:', error);
    alert('Error exporting report');
  }
}

function printReport() {
  try {
    window.print();
  } catch (error) {
    console.error('Error printing report:', error);
    alert('Error printing report');
  }
}

// ===== UTILITY FUNCTIONS =====
function generateCSV(measurements) {
  const headers = ['Measurement #', 'Distance (µm)', 'Start X', 'Start Y', 'End X', 'End Y'];
  const rows = measurements.map((m, i) => [
    i + 1,
    m.dist,
    m.x1,
    m.y1,
    m.x2,
    m.y2,
  ]);

  const csv = [
    headers.join(','),
    ...rows.map((row) => row.map((cell) => `"${cell}"`).join(',')),
  ].join('\n');

  return csv;
}

function generateReport() {
  const now = new Date();
  const dateStr = now.toLocaleDateString('id-ID', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const report = `
LAPORAN ANALISIS FENOTIPE MIKROSKOPI
PlantScope v1.0
=====================================

Tanggal: ${dateStr}
Waktu: ${now.toLocaleTimeString('id-ID')}

1. RINGKASAN EKSEKUTIF
---------------------
Analisis morfometri dilakukan dengan total ${AppState.measurements.length} pengukuran.
Kalibrasi: ${AppState.pixPerUm} px/µm

2. DATA PENGUKURAN
-----------------
${
  AppState.measurements.length > 0
    ? AppState.measurements
        .map(
          (m, i) => `Pengukuran ${i + 1}: ${m.dist} µm (dari ${m.x1},${m.y1} ke ${m.x2},${m.y2})`
        )
        .join('\n')
    : 'Tidak ada pengukuran'
}

3. ANOTASI
----------
Total anotasi: ${AppState.annotations.length}

4. KESIMPULAN
-------------
Analisis selesai dan data telah dicatat.
Untuk hasil lebih detail, lihat data export JSON atau CSV.

=====================================
Generated by PlantScope
`;

  return report;
}

function downloadFile(content, filename, mimeType) {
  try {
    const blob = new Blob([content], { type: mimeType });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  } catch (error) {
    console.error('Error downloading file:', error);
    throw error;
  }
}
